// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7z6nc9gPVjNell31-QmRthKDWFEdYefM',
    appId: '1:875959382932:web:6afc135eedabdddcea1581',
    messagingSenderId: '875959382932',
    projectId: 'pactra-57387',
    authDomain: 'pactra-57387.firebaseapp.com',
    storageBucket: 'pactra-57387.appspot.com',
    measurementId: 'G-WPQD377HWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFxSBLW7QjB0ocu-7fxRnYuW-vRomyqEE',
    appId: '1:875959382932:android:268d128df9ce88d6ea1581',
    messagingSenderId: '875959382932',
    projectId: 'pactra-57387',
    storageBucket: 'pactra-57387.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn0zhR4KpQxZYjMZyJPIcptx5-TM3jDBk',
    appId: '1:875959382932:ios:b02469f5e68a66b9ea1581',
    messagingSenderId: '875959382932',
    projectId: 'pactra-57387',
    storageBucket: 'pactra-57387.appspot.com',
    iosBundleId: 'com.pactra.app',
  );

}